on : push 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: 
          docker build -t flask-app .
      - name: Run Docker container
        run: 
          docker run --name flask-container -d -p 5000:5000 flask-app

      - name: wait
        run: sleep 10

      - name: Test health endpoint
        run: |
            for i in $(seq 1 10); do
            curl -s http://localhost:5000/health && echo "App is up" && exit 0
            echo "Attempt $i failed, retrying in 5 seconds..."
            sleep 5
            done 
            echo "App failed to start" && exit 1

      - name: Shut down Docker container
        run: docker stop flask-app && docker rm flask-app     